global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ai-news-processor'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics'
    scheme: 'http'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
